# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.reportCrashes", false);
user_pref("app.update.interval", 604800);
user_pref("app.update.lastUpdateTime.background-update-timer", 1392193232);
user_pref("browser.cache.disk.capacity", 57856);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("consoleservice.enabled", true);
user_pref("device.storage.writable.name", "sdcard");
user_pref("dom.mozApps.maxLocalId", 1043);
user_pref("dom.mozApps.used", true);
user_pref("gecko.buildID", "20131009041203");
user_pref("gecko.mstone", "18.1");
user_pref("idle.lastDailyNotification", 1392195922);
user_pref("intl.accept_languages", "en-US, en");
user_pref("marionette.contentListener", false);
user_pref("marionette.force-local", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("ril.cellbroadcast.disabled", true);
user_pref("ril.lastKnownHomeNetwork", "466-97");
user_pref("ril.lastKnownNetwork", "466-97");
user_pref("ril.lastKnownSimMcc", "466");
user_pref("ril.mms.mmsc", "http://mms.catch.net.tw");
user_pref("ril.mms.mmsport", 80);
user_pref("ril.mms.mmsproxy", "10.1.1.2");
user_pref("ril.radio.disabled", false);
user_pref("storage.vacuum.last.index", 0);
