# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.reportCrashes", false);
user_pref("app.update.interval", 604800);
user_pref("app.update.lastUpdateTime.background-update-timer", 1392108439);
user_pref("app.update.url.override", "http://update.boot2gecko.org/inari/1.3.0/nightly/update_20140209164003.xml");
user_pref("browser.cache.disk.capacity", 57856);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("consoleservice.enabled", true);
user_pref("dom.mozApps.maxLocalId", 1041);
user_pref("dom.mozApps.used", true);
user_pref("gecko.buildID", "20130906043205");
user_pref("gecko.mstone", "18.0");
user_pref("idle.lastDailyNotification", 1392112495);
user_pref("intl.accept_languages", "en-US, en");
user_pref("marionette.contentListener", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("ril.data.mmsc", "");
user_pref("ril.data.mmsport", 0);
user_pref("ril.data.mmsproxy", "");
user_pref("ril.lastKnownHomeNetwork", "466-97");
user_pref("ril.lastKnownMcc", "466");
user_pref("ril.lastKnownNetwork", "466-97");
user_pref("storage.vacuum.last.index", 0);
